typography_spectrum: 0.024462364614009857
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.09716583252884448
  lightness: 0.2782967519015074
  saturation: 0.2165200507733971
  rhythmicContrast: 0.30924094654619694
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5111366310156882
analytics:
  google: null
  facebook: null
  twitter: null
name: Jaiman
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: J
purpose: []
